# Use Alpine 3.13 as the base image to get PHP 7.4
FROM node:17.3.0-alpine3.13

# Install Subversion (svn)
RUN apk add --no-cache subversion

# Install Bash
RUN apk add --no-cache bash

# List contents of /bin/ to verify bash installation
RUN ls /bin/

# Test Bash installation
RUN bash -c "echo 'Bash is installed and working!'"

# Install PHP 7.4 and WP-CLI dependencies
RUN apk update && apk add --no-cache \
    php7 \
    php7-cli \
    php7-phar \
    php7-mysqli \
    php7-json \
    php7-curl \
    php7-mbstring \
    php7-openssl \
    php7-xml \
    php7-simplexml \
    php7-tokenizer \
    php7-ctype \
    php7-dom \
    php7-xmlwriter \
    php7-xmlreader \
    php7-pdo \
    php7-pdo_mysql \
    php7-zlib \
    php7-zip \
    php7-fileinfo \
    curl \
    less \
    mariadb-client \
    git \
    unzip \
    wget

# Create a symlink for PHP 7.4 to use the php command
#RUN ln -s /usr/bin/php7 /usr/bin/php

# Set PHP max execution time to unlimited
RUN echo "max_execution_time=0" >> /etc/php7/php.ini

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Verify Composer installation
RUN composer --version

# Verify PHP installation
RUN which php && php -v

# Install WP-CLI
RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && \
    chmod +x wp-cli.phar && \
    mv wp-cli.phar /usr/local/bin/wp

# Set working directory
WORKDIR /www-node/

# Default command
CMD ["bash"]
