# Use the official Node.js Alpine image as the base image
FROM node:20.11.0-alpine

# Install Subversion (svn)
RUN apk add --no-cache subversion

# Install Bash
RUN apk add --no-cache bash

# List contents of /bin/ to verify bash installation
RUN ls /bin/

# Test Bash installation
RUN bash -c "echo 'Bash is installed and working!'"

# Install PHP 8.1 and WP-CLI dependencies
RUN apk update && apk add --no-cache \
    php81 \
    php81-cli \
    php81-phar \
    php81-mysqli \
    php81-json \
    php81-curl \
    php81-mbstring \
    php81-openssl \
    php81-xml \
    php81-simplexml \
    php81-tokenizer \
    php81-ctype \
    php81-dom \
    php81-xmlwriter \
    php81-xmlreader \
    php81-pdo \
    php81-pdo_mysql \
    php81-zlib \
    php81-zip \
    php81-fileinfo \
    curl \
    less \
    mariadb-client \
    git \
    unzip \
    wget

# Create a symlink for PHP 8.1 to use the php command
RUN ln -s /usr/bin/php81 /usr/bin/php

# Set PHP max execution time to unlimited
RUN echo "max_execution_time=0" >> /etc/php81/php.ini

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Verify Composer installation
RUN composer --version

# Verify PHP installation
RUN which php && php -v

# Install WP-CLI
RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && \
    chmod +x wp-cli.phar && \
    mv wp-cli.phar /usr/local/bin/wp

# Set working directory
WORKDIR /www-node/

# Default command
CMD ["bash"]
